export type Truck = {
  id: string;
  truckId: string;
  branchRegisteredTo: string;
  registrationNumber: string;
  manufacturer: string;
  modelName: string;
  truckType: string;
  truckPhotosFileName: string | null;
  chassisNumber: string;
  yearOfManufacture: string;
  tyreLayout: string;
  fuelCapacity: string;
  odometerDuringPurchase: string;
  odometer: string;
  rcValidityDate: string;
  rcExpenses: string;
  rcDocumentUrl: string | null;
  fcExpiryDate: string;
  fcDocumentFileName: string | null;
  fcExpenses: string;
  roadTaxDate: string;
  roadTaxNumber: string;
  roadTaxDocumentFileName: string | null;
  roadTaxExpenses: string;
  insuranceExpiryDate: string;
  insuranceExpenses: string;
  insuranceDocumentProofFileName: string | null;
  nationalPermitNumber: string;
  nationalPermitDate: string;
  nationalPermitProofFileName: string | null;
  nationalPermitExpenses: string;
  localPermitNumber: string;
  localPermitDate: string;
  localPermitProofFileName: string | null;
  localPermitExpenses: string;
  pollutionCertificateDate: string;
  pollutionCertificateNumber: string;
  pollutionCertificateProofFileName: string | null;
  pollutionCertificateExpenses: string;
};
