# --- path bootstrap ---
import os as _os, sys as _sys
_BACKEND = _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__)))
if _BACKEND not in _sys.path:
    _sys.path.insert(0, _BACKEND)
_os.chdir(_BACKEND)
# ----------------------

"""
Translates Excel-format tyre positions in tyre_fitment_records
into the frontend position strings generated by getTyrePositions().

Excel format:   N-AXLE-L/R-OUT/IN  (e.g. "5-AXLE-L-OUT")  and  "SPARE"
Frontend format: "Axle N - Left 1"  /  "Tractor Head - Axle 2 - Right 2"  /  "Spare"

Layout axle structures (derived from tyre-layouts.ts):
  14+1              : axles 1-3 single, axles 4-5 dual  (5 axles, no unit prefix)
  12+1              : axles 1-2 single, axles 3-4 dual  (4 axles, no unit prefix)
  10+1              : axle 1 single,    axles 2-3 dual  (3 axles, no unit prefix)
  18+1-tractor-trailer : Tractor Head (axle1=single, axle2=dual)
                         Trailer (axles 3-5 all dual)
  14+1-tractor-trailer : Tractor Head (axle1=single, axle2=dual)
                         Trailer (axles 3-4 all dual)

Wheel suffix rule: OUT -> 1 (outer/first), IN -> 2 (inner/second)
Single-axle positions have no wheel number suffix.
"""

from database import SessionLocal
from models import Truck, TyreFitmentRecord


def translate_position(excel_pos: str, tyre_layout: str) -> str:
    p = excel_pos.strip().upper()
    if p == "SPARE":
        return "Spare"

    parts = p.split("-")
    if len(parts) < 4:
        raise ValueError(f"Unrecognised position format: {excel_pos!r}")

    axle_num = int(parts[0])
    side = "Left" if parts[2] == "L" else "Right"
    wheel = "1" if parts[3] == "OUT" else "2"  # OUT=outer=1, IN=inner=2

    if tyre_layout == "14+1":
        # Axles 1, 2, 3 → single (L-OUT / R-OUT only, no suffix)
        # Axles 4, 5    → dual   (L-OUT/L-IN → Left 1/2; R-OUT/R-IN → Right 1/2)
        if axle_num in (1, 2, 3):
            return f"Axle {axle_num} - {side}"
        if axle_num in (4, 5):
            return f"Axle {axle_num} - {side} {wheel}"

    elif tyre_layout == "12+1":
        # Axles 1, 2 → single; Axles 3, 4 → dual
        if axle_num in (1, 2):
            return f"Axle {axle_num} - {side}"
        if axle_num in (3, 4):
            return f"Axle {axle_num} - {side} {wheel}"

    elif tyre_layout == "10+1":
        # Axle 1 → single; Axles 2, 3 → dual
        if axle_num == 1:
            return f"Axle 1 - {side}"
        if axle_num in (2, 3):
            return f"Axle {axle_num} - {side} {wheel}"

    elif tyre_layout == "18+1-tractor-trailer":
        # Tractor Head: axle1=single, axle2=dual
        # Trailer:      axles 3-5 all dual
        if axle_num == 1:
            return f"Tractor Head - Axle 1 - {side}"
        if axle_num == 2:
            return f"Tractor Head - Axle 2 - {side} {wheel}"
        if axle_num in (3, 4, 5):
            return f"Trailer - Axle {axle_num - 2} - {side} {wheel}"

    elif tyre_layout == "14+1-tractor-trailer":
        # Tractor Head: axle1=single, axle2=dual
        # Trailer:      axles 3-4 all dual
        if axle_num == 1:
            return f"Tractor Head - Axle 1 - {side}"
        if axle_num == 2:
            return f"Tractor Head - Axle 2 - {side} {wheel}"
        if axle_num in (3, 4):
            return f"Trailer - Axle {axle_num - 2} - {side} {wheel}"

    raise ValueError(
        f"No rule for position {excel_pos!r} with axle_num={axle_num} on layout {tyre_layout!r}"
    )


def main():
    db = SessionLocal()

    # Build truck_id → tyre_layout map
    layout_map = {t.id: t.tyre_layout for t in db.query(Truck).all()}

    records = db.query(TyreFitmentRecord).all()
    print(f"Translating {len(records)} fitment positions...")

    ok = 0
    errors = []
    for rec in records:
        tyre_layout = layout_map.get(rec.truck_id)
        if not tyre_layout:
            errors.append(f"fitment id={rec.id}: truck_id={rec.truck_id} not found")
            continue
        try:
            new_pos = translate_position(rec.position, tyre_layout)
            rec.position = new_pos
            ok += 1
        except ValueError as exc:
            errors.append(f"fitment id={rec.id} truck_id={rec.truck_id} layout={tyre_layout}: {exc}")

    if errors:
        db.rollback()
        print(f"\n[ABORT] {len(errors)} error(s) — no changes committed:")
        for e in errors:
            print(f"  {e}")
    else:
        db.commit()
        print(f"Done — {ok} positions translated, 0 errors.")

    db.close()


if __name__ == "__main__":
    main()
